<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Content Update="wwwroot\img\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.12" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\bundles\scripts.js" />
      <_ContentIncludedByDefault Remove="wwwroot\bundles\scripts.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\bundles\scripts.min.js.gz" />
      <_ContentIncludedByDefault Remove="wwwroot\bundles\styles.css" />
      <_ContentIncludedByDefault Remove="wwwroot\bundles\styles.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\bundles\styles.min.css.gz" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Components\DatePickerWidgets\DatePickerMonth.razor" />
      <UpToDateCheckInput Remove="Components\DatePickerWidgets\DateRangePickerMonth.razor" />
      <UpToDateCheckInput Remove="Components\DatePickerWidgets\DateRangePickerMonths.razor" />
      <UpToDateCheckInput Remove="Components\DatePickerWidgets\TimePicker.razor" />
    </ItemGroup>

</Project>
